### PR TITLE
Fix for #142, #144, #146,  get warning "Date outside of valid range: " and error "Uncaught RangeError" when using min-date or max-date

### PR DESCRIPTION
**Pull request by julie2013**
1. # 142
   
   `<paper-date-picker min-date="Apr 01, 2015" max-date="Oct 19, 2017" date="Sep 20, 2016"></paper-date-picker>`

When I click ">", it only navigates to Oct 2016, and stuck there. I could not navigate to next month after Oct 2016. Also when I click "<" to navigate to previous month until Apr 2015, then click ">", the window is stuck on Oct 2015. I also can not navigate to next month after Oct, 2015.
1. #144 

`<paper-date-picker min-date="August 10, 2016" max-date="January 13, 2019"  date="Sep 20, 2016"></paper-date-picker>`
Click the year number from calendar and choose "2019" from year list, the new date will be "Sep 20 2019". The console will continue to output warning messages "Date outside of valid range: " (paper-calendar.html line 628). After thousands of warnings, a new error "Uncaught exception" will output , later another error "Uncaught RangeError: Maximum call stack size exceeded."(Chrome).

In Firefox, the browser will be frozen and could not response any more.
1. #146 
   `<paper-date-picker min-date="Dec 12, 2015" max-date="Aug 10, 2017"  date="Sep 20, 2016"></paper-date-picker>`
   Similar to #144, select "2015" from year list, and get the same behaviour as in #144 .

### CODE REVIEW

**Comment by josheverett** [comment]
When can we expect to see this fix merged in? The max-date feature is otherwise unusable.

**Comment by PavanInala** [comment]
Hi, In our application we are using date-picker and we need min and max date functionality, can you please tell us when this fix will be merged? Thanks in advance.

**Comment by adi130987** [comment]
Hello, any updates regarding this issues?

**Comment by julie2013** [comment]
Need someone who has write access to merge this pull request.

**Pull request merged**
