### PR TITLE
swipe fixes & little optimizations

### PR DESCRIPTION
**Pull request by Zecat**
The animation is now working when swiping with speed > FLICK_SPEED, and on tap on left/right arrows.

### CODE REVIEW

**Comment by Zecat** [comment]
I added various style modifications

**Comment by Zecat** [comment]
paper-ripple implemented !

**Comment by Zecat** [comment]
Fix #51

**Comment by bendavis78** [comment]
Thanks for the PR. This includes a huge number of changes, many of which are unrelated, so I can't really merge it all at once. There are some commits that I don't think should be applied, however I want to look into your changes in more detail. Could you create pull requests for individual bugfixes and/or features?

**Pull request closed without merging**
